name: ci

on:
  pull_request:
    branches: [ main ]
  push:
    branches: [ main ]

jobs:
  build-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Cache pip
        uses: actions/cache@v4
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # P0: 린트는 경고만 남기고 통과(코드 정리 전 단계)
      - name: Ruff (soft)
        run: |
          ruff check . --fix --exit-zero
          ruff format . || true

      - name: Mypy
        run: |
          mypy --install-types --non-interactive .

      - name: Bandit
        run: |
          bandit -q -r . -x tests

      - name: Pytest
        run: |
          pytest -q --maxfail=1 --disable-warnings
